// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/store.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetLastEventIDRequest struct {
	Filter               *Filter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastEventIDRequest) Reset()         { *m = GetLastEventIDRequest{} }
func (m *GetLastEventIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastEventIDRequest) ProtoMessage()    {}
func (*GetLastEventIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{0}
}

func (m *GetLastEventIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastEventIDRequest.Unmarshal(m, b)
}
func (m *GetLastEventIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastEventIDRequest.Marshal(b, m, deterministic)
}
func (m *GetLastEventIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastEventIDRequest.Merge(m, src)
}
func (m *GetLastEventIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastEventIDRequest.Size(m)
}
func (m *GetLastEventIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastEventIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastEventIDRequest proto.InternalMessageInfo

func (m *GetLastEventIDRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type GetLastEventIDReply struct {
	EventId              string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastEventIDReply) Reset()         { *m = GetLastEventIDReply{} }
func (m *GetLastEventIDReply) String() string { return proto.CompactTextString(m) }
func (*GetLastEventIDReply) ProtoMessage()    {}
func (*GetLastEventIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{1}
}

func (m *GetLastEventIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastEventIDReply.Unmarshal(m, b)
}
func (m *GetLastEventIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastEventIDReply.Marshal(b, m, deterministic)
}
func (m *GetLastEventIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastEventIDReply.Merge(m, src)
}
func (m *GetLastEventIDReply) XXX_Size() int {
	return xxx_messageInfo_GetLastEventIDReply.Size(m)
}
func (m *GetLastEventIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastEventIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastEventIDReply proto.InternalMessageInfo

func (m *GetLastEventIDReply) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

type GetEventsRequest struct {
	AfterEventId         string   `protobuf:"bytes,1,opt,name=after_event_id,json=afterEventId,proto3" json:"after_event_id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter               *Filter  `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{2}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetAfterEventId() string {
	if m != nil {
		return m.AfterEventId
	}
	return ""
}

func (m *GetEventsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetEventsRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Filter struct {
	AggregateTypes       []string `protobuf:"bytes,1,rep,name=aggregate_types,json=aggregateTypes,proto3" json:"aggregate_types,omitempty"`
	Labels               []*Label `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{3}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetAggregateTypes() []string {
	if m != nil {
		return m.AggregateTypes
	}
	return nil
}

func (m *Filter) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Label struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{4}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetEventsReply struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsReply) Reset()         { *m = GetEventsReply{} }
func (m *GetEventsReply) String() string { return proto.CompactTextString(m) }
func (*GetEventsReply) ProtoMessage()    {}
func (*GetEventsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{5}
}

func (m *GetEventsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsReply.Unmarshal(m, b)
}
func (m *GetEventsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsReply.Marshal(b, m, deterministic)
}
func (m *GetEventsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsReply.Merge(m, src)
}
func (m *GetEventsReply) XXX_Size() int {
	return xxx_messageInfo_GetEventsReply.Size(m)
}
func (m *GetEventsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsReply proto.InternalMessageInfo

func (m *GetEventsReply) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AggregateId          string               `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateVersion     int32                `protobuf:"varint,3,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	AggregateType        string               `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Body                 string               `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	IdempotencyKey       string               `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Labels               string               `protobuf:"bytes,8,opt,name=labels,proto3" json:"labels,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26c0cbd0e78c93, []int{6}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Event) GetAggregateVersion() int32 {
	if m != nil {
		return m.AggregateVersion
	}
	return 0
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Event) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Event) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Event) GetIdempotencyKey() string {
	if m != nil {
		return m.IdempotencyKey
	}
	return ""
}

func (m *Event) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLastEventIDRequest)(nil), "proto.GetLastEventIDRequest")
	proto.RegisterType((*GetLastEventIDReply)(nil), "proto.GetLastEventIDReply")
	proto.RegisterType((*GetEventsRequest)(nil), "proto.GetEventsRequest")
	proto.RegisterType((*Filter)(nil), "proto.Filter")
	proto.RegisterType((*Label)(nil), "proto.Label")
	proto.RegisterType((*GetEventsReply)(nil), "proto.GetEventsReply")
	proto.RegisterType((*Event)(nil), "proto.Event")
}

func init() {
	proto.RegisterFile("api/proto/store.proto", fileDescriptor_2e26c0cbd0e78c93)
}

var fileDescriptor_2e26c0cbd0e78c93 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x6d, 0x7b, 0xc9, 0x5d, 0xa6, 0xbd, 0x58, 0x57, 0xab, 0xb1, 0x08, 0xd6, 0xd0, 0xc3,
	0x82, 0xd0, 0x4a, 0x05, 0xc1, 0x07, 0x05, 0x41, 0x3d, 0x8a, 0x7d, 0x5a, 0x0f, 0x7d, 0x0c, 0xdb,
	0xdb, 0x69, 0x58, 0x2e, 0x6d, 0x62, 0xb2, 0x2d, 0xe4, 0x7b, 0xf8, 0x49, 0xfc, 0x84, 0xb2, 0xb3,
	0x69, 0xda, 0x9e, 0x7a, 0x4f, 0x99, 0xf9, 0xfd, 0x67, 0x76, 0x27, 0xff, 0x4c, 0xa0, 0x27, 0x32,
	0x35, 0xc9, 0xf2, 0x54, 0xa7, 0x93, 0x42, 0xa7, 0x39, 0x8e, 0x29, 0x66, 0x0e, 0x3d, 0xfa, 0xcf,
	0xe3, 0x34, 0x8d, 0x13, 0xb4, 0x05, 0x8b, 0xcd, 0x72, 0xa2, 0xd5, 0x0a, 0x0b, 0x2d, 0x56, 0x99,
	0xad, 0x0b, 0x3f, 0x40, 0xef, 0x12, 0xf5, 0x5c, 0x14, 0xfa, 0xf3, 0x16, 0xd7, 0x7a, 0xf6, 0x89,
	0xe3, 0xcf, 0x0d, 0x16, 0x9a, 0x5d, 0x80, 0xbb, 0x54, 0x89, 0xc6, 0x3c, 0x68, 0x0c, 0x1a, 0xa3,
	0xf6, 0xf4, 0xdc, 0x36, 0x8c, 0xbf, 0x10, 0xe4, 0x95, 0x18, 0xbe, 0x86, 0x87, 0xb7, 0xfb, 0xb3,
	0xa4, 0x64, 0x4f, 0xe1, 0x0c, 0x4d, 0x1e, 0x29, 0x49, 0xfd, 0x1e, 0x3f, 0xa5, 0x7c, 0x26, 0xc3,
	0x0d, 0x74, 0x2f, 0xd1, 0x56, 0x17, 0xbb, 0xcb, 0x86, 0xe0, 0x8b, 0xa5, 0xc6, 0x3c, 0xba, 0xd5,
	0xd4, 0x21, 0x6a, 0x4f, 0x96, 0xec, 0x11, 0x38, 0x89, 0x5a, 0x29, 0x1d, 0x34, 0x07, 0x8d, 0x91,
	0xc3, 0x6d, 0x72, 0x30, 0x68, 0xeb, 0xae, 0x41, 0x7f, 0x80, 0x6b, 0x09, 0x7b, 0x09, 0xf7, 0x45,
	0x1c, 0xe7, 0x18, 0x0b, 0x8d, 0x91, 0x2e, 0x33, 0x2c, 0x82, 0xc6, 0xa0, 0x35, 0xf2, 0xb8, 0x5f,
	0xe3, 0x2b, 0x43, 0xd9, 0x10, 0xdc, 0x44, 0x2c, 0x30, 0x29, 0x82, 0xe6, 0xa0, 0x35, 0x6a, 0x4f,
	0x3b, 0xd5, 0xc9, 0x73, 0x03, 0x79, 0xa5, 0x85, 0x13, 0x70, 0x08, 0xb0, 0x2e, 0xb4, 0x6e, 0xb0,
	0xac, 0x26, 0x37, 0xa1, 0x19, 0x78, 0x2b, 0x92, 0x0d, 0xd2, 0xc0, 0x1e, 0xb7, 0x49, 0xf8, 0x16,
	0xfc, 0x03, 0x03, 0x8c, 0x5b, 0x43, 0x70, 0xe9, 0xc5, 0xed, 0x20, 0xfb, 0x8b, 0xa8, 0x86, 0x57,
	0x5a, 0xf8, 0xbb, 0x09, 0x0e, 0x11, 0xe6, 0x43, 0xb3, 0xb6, 0xa8, 0xa9, 0x24, 0x7b, 0x01, 0x9d,
	0xfd, 0x1b, 0x29, 0x59, 0x5d, 0xd7, 0xae, 0xd9, 0x4c, 0xb2, 0x57, 0xf0, 0x60, 0x5f, 0xb2, 0xc5,
	0xbc, 0x50, 0xe9, 0x9a, 0x0c, 0x73, 0x78, 0xb7, 0x16, 0xbe, 0x5b, 0xce, 0x2e, 0xc0, 0x3f, 0x76,
	0x28, 0x38, 0xa1, 0x13, 0xcf, 0x8f, 0x0c, 0x62, 0x0c, 0x4e, 0x6e, 0xd4, 0x5a, 0x06, 0x0e, 0x89,
	0x14, 0x1b, 0xb6, 0x48, 0x65, 0x19, 0xb8, 0x96, 0x99, 0xd8, 0x18, 0xae, 0x24, 0xae, 0xb2, 0x54,
	0xe3, 0xfa, 0xba, 0x8c, 0x8c, 0x49, 0xa7, 0x24, 0xfb, 0x07, 0xf8, 0x2b, 0x96, 0xec, 0x71, 0x6d,
	0xf8, 0x19, 0xe9, 0x55, 0xc6, 0xde, 0x01, 0x5c, 0xe7, 0x28, 0x34, 0xca, 0x48, 0xe8, 0xc0, 0xa3,
	0xcf, 0xdc, 0x1f, 0xdb, 0xd5, 0x1e, 0xef, 0x56, 0x7b, 0x7c, 0xb5, 0x5b, 0x6d, 0xee, 0x55, 0xd5,
	0x1f, 0xf5, 0xf4, 0x57, 0x03, 0x9c, 0x6f, 0xe6, 0xbf, 0x60, 0x73, 0xb2, 0xfd, 0x60, 0x53, 0xd9,
	0xb3, 0xca, 0xe6, 0x7f, 0xfe, 0x00, 0xfd, 0xfe, 0x7f, 0xd4, 0x2c, 0x29, 0xc3, 0x7b, 0xec, 0x3d,
	0x78, 0xf5, 0x47, 0x64, 0x4f, 0xf6, 0xa5, 0x47, 0x7b, 0xdd, 0xef, 0xfd, 0x2d, 0x50, 0xfb, 0xc2,
	0x25, 0xfe, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x1e, 0xee, 0xef, 0xbe, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	GetLastEventID(ctx context.Context, in *GetLastEventIDRequest, opts ...grpc.CallOption) (*GetLastEventIDReply, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsReply, error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) GetLastEventID(ctx context.Context, in *GetLastEventIDRequest, opts ...grpc.CallOption) (*GetLastEventIDReply, error) {
	out := new(GetLastEventIDReply)
	err := c.cc.Invoke(ctx, "/proto.Store/GetLastEventID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsReply, error) {
	out := new(GetEventsReply)
	err := c.cc.Invoke(ctx, "/proto.Store/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	GetLastEventID(context.Context, *GetLastEventIDRequest) (*GetLastEventIDReply, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsReply, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) GetLastEventID(ctx context.Context, req *GetLastEventIDRequest) (*GetLastEventIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastEventID not implemented")
}
func (*UnimplementedStoreServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_GetLastEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetLastEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/GetLastEventID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetLastEventID(ctx, req.(*GetLastEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastEventID",
			Handler:    _Store_GetLastEventID_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Store_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/store.proto",
}
